[package]
name = "random-commit"
version = "0.1.0"
authors = ["Dmitry Porunov <hi@dmitry.email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.3"
actix-web = "3.3.2"
env_logger = "0.8.3"
askama = "0.9"